version: "3.9"
services:
  kotlin-graddle-sample-db:
    container_name: kotlin-gradle-sample-db
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  backend:
    container_name: kotlin-sample-sample-backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      - spring.datasource.url=jdbc:postgresql://kotlin-gradle-sample-db:5432/postgres
    ports:
      - "8080:8080"
    depends_on:
      - kotlin-graddle-sample-db
